package chapter04.classes.and.interfaces;

import interfaces.ILesson;

public class Item19_DesignAndDocumentForInheritanceOrElseProhibitIt implements ILesson {

    @Override
    public void doLesson() {
        /*
         * For each public or protected method, the documentation must indicate which overridable methods the method invokes,
         * in what sequence, and how the results of each invocation affect subsequent processing
         */

        /*
         * The description is in a special section of the specification, labeled “Implementation Requirements,” which is generated by the Javadoc tag @implSpec. This section describes the inner workings of the method
         */
    }
}
